"""
Django settings for Nexus project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
from os.path import join, dirname
from pathlib import Path
from urllib.parse import urlparse

load_dotenv()
LS_DB_NAME = os.environ.get("LS_DB_NAME")
LS_DB_USER = os.environ.get("LS_DB_USER")
LS_DB_PASSWORD = os.environ.get("LS_DB_PASSWORD")
LS_DB_HOST = os.environ.get("LS_DB_HOST")
LS_DB_PORT = os.environ.get("LS_DB_PORT")
GAME_DB_NAME = os.environ.get("GAME_DB_NAME")
GAME_DB_USER = os.environ.get("GAME_DB_USER")
GAME_DB_PASSWORD = os.environ.get("GAME_DB_PASSWORD")
GAME_DB_HOST = os.environ.get("GAME_DB_HOST")
GAME_DB_PORT = os.environ.get("GAME_DB_PORT")
DJANGO_APP_DB_NAME = os.environ.get("DJANGO_APP_DB_NAME")
DJANGO_APP_DB_USER = os.environ.get("DJANGO_APP_DB_USER")
DJANGO_APP_DB_PASSWORD = os.environ.get("DJANGO_APP_DB_PASSWORD")
DJANGO_APP_DB_HOST = os.environ.get("DJANGO_APP_DB_HOST")
DJANGO_APP_DB_PORT = os.environ.get("DJANGO_APP_DB_PORT")
DJANGO_EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND")
DJANGO_EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST")
DJANGO_EMAIL_PORT = os.environ.get("DJANGO_EMAIL_PORT")
DJANGO_EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS")
DJANGO_EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER")
DJANGO_EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD")
DJANGO_DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL")
PETITION_DISCORD_WEBHOOK_URL = os.environ.get("PETITION_DISCORD_WEBHOOK_URL", "")
RAID_SCHEDULER_DISCORD_WEBHOOK_URL = os.environ.get("RAID_SCHEDULER_DISCORD_WEBHOOK_URL", "")
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
SITE_NAME = os.environ.get("SITE_NAME", "Nexus")

# Current server expansion (0=Classic, 1=Kunark, 2=Velious, 3=Luclin, 4=PoP, 5=LoY, 6=LDoN)
SERVER_EXPANSION = int(os.environ.get("SERVER_EXPANSION", 5))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_APP_SECRET_KEY", "INSECURE")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ['DEBUG'] == 'TRUE'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'common.apps.CommonConfig',
    'characters.apps.CharactersConfig',
    'character_transfer.apps.CharacterTransferConfig',
    'debug_toolbar',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_gravatar',
    'django_jsonform',
    'django_otp',
    'django_otp.plugins.otp_totp',   # TOTP (Google Authenticator, Authy)
    'django_otp.plugins.otp_static', # Backup codes
    'django_otp_webauthn',           # Passkeys / WebAuthn
    'rest_framework',                # Required by django-otp-webauthn
    'django_tables2',
    'dkp.apps.DkpConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'factions.apps.FactionConfig',
    'items.apps.ItemConfig',
    'magelo.apps.MageloConfig',
    'mdeditor',
    'npcs.apps.NpcsConfig',
    'patch.apps.PatchConfig',
    'pets.apps.PetsConfig',
    'quests.apps.QuestsConfig',
    'recipes.apps.RecipesConfig',
    'spells.apps.SpellsConfig',
    'zones.apps.ZonesConfig',
    'raid_scheduler.apps.RaidSchedulerConfig',
    'petitions.apps.PetitionsConfig',
]

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

CRISPY_TEMPLATE_PACK = 'bootstrap5'
DJANGO_TABLES2_TEMPLATE = 'django_tables2/bootstrap5-responsive.html'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'Nexus.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'Nexus.middleware.StaffMFARequiredMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

ROOT_URLCONF = 'Nexus.urls'
# Custom admin URL for security (set via environment variable)
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin/')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'dkp.context_processors.dkp_context',
                'Nexus.context_processors.navigation_context',
                'petitions.context_processors.petition_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nexus.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_ROUTERS = ['accounts.LoginServerRouter.LoginServerRouter',
                    'accounts.GameServerRouter.GameServerRouter',
                    'common.GameServerRouter.GameServerRouter']

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DJANGO_APP_DB_NAME,
        "USER": DJANGO_APP_DB_USER,
        "PASSWORD": DJANGO_APP_DB_PASSWORD,
        "HOST": DJANGO_APP_DB_HOST,
        "PORT": DJANGO_APP_DB_PORT,
        "OPTIONS": {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 60,
            'read_timeout': 120,
            'write_timeout': 120,
        },
    },
    "game_database": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": GAME_DB_NAME,
        "USER": GAME_DB_USER,
        "PASSWORD": GAME_DB_PASSWORD,
        "HOST": GAME_DB_HOST,
        "PORT": GAME_DB_PORT
    },
    "login_server_database": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": LS_DB_NAME,
        "USER": LS_DB_USER,
        "PASSWORD": LS_DB_PASSWORD,
        "HOST": LS_DB_HOST,
        "PORT": LS_DB_PORT
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# Only enable strict security in production
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy
# Content Security Policy - protocol-aware
if DEBUG:
    # Development: allow both http and https (no protocol specified)
    protocol = ""
else:
    # Production: enforce https only
    protocol = "https://"

SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ["'self'"],
    'script-src': [
        "'self'",
        "'unsafe-inline'",
        f"{protocol}cdnjs.cloudflare.com",
        f"{protocol}cdn.jsdelivr.net",
        f"{protocol}ajax.googleapis.com",
        f"{protocol}static.cloudflareinsights.com",
        f"{protocol}code.jquery.com",
        f"{protocol}unpkg.com",
        f"{protocol}cdn.datatables.net",
    ],
    'style-src': [
        "'self'",
        "'unsafe-inline'",
        f"{protocol}fonts.googleapis.com",
        f"{protocol}use.fontawesome.com",
        f"{protocol}cdn.jsdelivr.net",
        f"{protocol}cdn.datatables.net",
    ],
    'font-src': [
        "'self'",
        f"{protocol}fonts.gstatic.com",
        f"{protocol}use.fontawesome.com",
    ],
    'img-src': [
        "'self'",
        "data:",
        "blob:",
        f"{protocol}*.cloudflare.com",
        f"{protocol}secure.gravatar.com",
        f"{protocol}media.eqarchives.com",
    ],
    'connect-src': [
        "'self'",
        "blob:",
        f"{protocol}ajax.googleapis.com",
        f"{protocol}static.cloudflareinsights.com",
    ],
    'frame-ancestors': ["'none'"],
    'base-uri': ["'self'"],
    'form-action': ["'self'"],
}

# Convert CSP dict to header string
CSP_DIRECTIVES = []
for directive, sources in SECURE_CONTENT_SECURITY_POLICY.items():
    CSP_DIRECTIVES.append(f"{directive.replace('_', '-')} {' '.join(sources)}")
SECURE_CONTENT_SECURITY_POLICY = '; '.join(CSP_DIRECTIVES)

# Permissions Policy
SECURE_PERMISSIONS_POLICY = {
    'geolocation': [],
    'microphone': [],
    'camera': [],
    'payment': [],
    'usb': [],
    'magnetometer': [],
    'accelerometer': [],
    'gyroscope': [],
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Where you put your source files
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'logfile': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'server.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['logfile'],
            'level': 'WARNING',
        },
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
        'Nexus.security': {
            'handlers': ['logfile'],
            'level': 'INFO',
            'propagate': False,
        },
        'raid_scheduler': {
            'handlers': ['logfile'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

MDEDITOR_CONFIGS = {
    'default': {
        'width': '100% ',  # Custom edit box width
        'height': 500,  # Custom edit box height
        'toolbar': ["undo", "redo", "|",
                    "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
                    "h1", "h2", "h3", "h5", "h6", "|",
                    "list-ul", "list-ol", "hr", "|",
                    "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
                    "emoji", "html-entities", "pagebreak", "goto-line", "|",
                    "help", "info",
                    "||", "preview", "watch", "fullscreen"],  # custom edit box toolbar
        # image upload format type
        'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp", "svg"],
        'image_folder': 'editor',  # image save the folder name
        'theme': 'default',  # edit box theme, dark / default
        'preview_theme': 'default',  # Preview area theme, dark / default
        'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
        'toolbar_autofixed': False,  # Whether the toolbar capitals
        'search_replace': True,  # Whether to open the search for replacement
        'emoji': True,  # whether to open the expression function
        'tex': True,  # whether to open the tex chart function
        'flow_chart': False,  # whether to open the flow chart function
        'sequence': False,  # Whether to open the sequence diagram function
        'watch': True,  # Live preview
        'lineWrapping': True,  # lineWrapping
        'lineNumbers': True,  # lineNumbers
        'language': 'en'  # zh / en / es
    }
}

# enabling media uploads
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/media/'

# WebAuthn / Passkeys (django-otp-webauthn)
_parsed_site = urlparse(SITE_URL)
OTP_WEBAUTHN_RP_ID = _parsed_site.hostname          # e.g. 'example.com' or 'localhost'
OTP_WEBAUTHN_RP_NAME = 'Project Miragul'
OTP_WEBAUTHN_ALLOWED_ORIGINS = [f"{_parsed_site.scheme}://{_parsed_site.netloc}"]
OTP_WEBAUTHN_ALLOW_PASSWORDLESS_LOGIN = True         # Passkeys can replace password entirely

# In development the Django server runs plain HTTP even when SITE_URL uses https,
# so add the http variant so the WebAuthn origin check passes either way.
if DEBUG:
    _http_origin = f"http://{_parsed_site.netloc}"
    if _http_origin not in OTP_WEBAUTHN_ALLOWED_ORIGINS:
        OTP_WEBAUTHN_ALLOWED_ORIGINS = OTP_WEBAUTHN_ALLOWED_ORIGINS + [_http_origin]

LOGIN_REDIRECT_URL = '/accounts/'

# Email backend — falls back to console (prints to terminal) if not configured in .env
EMAIL_BACKEND = DJANGO_EMAIL_BACKEND or 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = DJANGO_EMAIL_HOST
EMAIL_PORT = DJANGO_EMAIL_PORT
EMAIL_USE_TLS = DJANGO_EMAIL_USE_TLS
EMAIL_HOST_USER = DJANGO_EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = DJANGO_EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = DJANGO_DEFAULT_FROM_EMAIL
